export const tarefas = [
    {
        id: 1,
        title: "Tarefa 1",
        description: "lorem ipsulum dolor sit a met",
        aFazer: false,
        fazendo: true,
        feito: false,
    },
    {
        id: 2,
        title: "Tarefa 2",
        description: "lorem ipsulum dolor sit a met",
        aFazer: true,
        fazendo: false,
        feito: false,
    },
    {
        id: 3,
        title: "Tarefa 3",
        description: "lorem ipsulum dolor sit a met",
        aFazer: true,
        fazendo: false,
        feito: false,
    },
    {
        id: 4,
        title: "Tarefa 4",
        description: "lorem ipsulum dolor sit a met",
        aFazer: true,
        fazendo: false,
        feito: false,
    },
    {
        id: 5,
        title: "Tarefa 5",
        description: "lorem ipsulum dolor sit a met",
        aFazer: true,
        fazendo: false,
        feito: false,
    },
];
